export const USER_ROLES = { PM: "PM", ADMIN: "Admin", DEV: "Dev" };
// export const PAGE_URLS = {
//   LOGIN: "/login",
//   REPORT: "/report",
//   HOMEPAGE: "/",
//   PROJECTS: "/projects",
//   MANAGE: "/manage",
//   NEWPROJECT: "/projects/newprojects",
//   REPORT_MEMBER: "member",
//   REPORT_DETAIL: "/report/detail",
//   REPORT_PROJECT: "project",
//   PROJECTS_ITEM: "/projects/projectitem",
//   EDITPROJECT: "/projects/editproject",
// };
export const PAGE_URLS = {
  LOGIN: "/login",
  REGISTER: "/register",
  REPORT: "/report",
  HOMEPAGE: "/",
  PROJECTS: "/projects",
  MANAGE: "/manage",
  NEWPROJECT: "/newprojects",
  REPORT_MEMBER: "member",
  REPORT_DETAIL: "detail",
  REPORT_PROJECT: "project",
  PROJECTS_ITEM: "/projectitem",
  EDITPROJECT: "/editproject",
};

export const ACTION_EDIT_TIME = {
  EARLIER: "earlier",
  LATER: "later",
};

export const OUT_DATE_EDIT_TIME = {
  EARLIER: "outDateEarlier",
  LATER: "outDateLater",
};

export const FORMAT_DATE = "DD-MM-YYYY";
export const FORMAT_DATE_REPORT_DETAIL = "DD/MM/YYYY";
export const FORMAT_TIME = "h:mm A";

export const SERVER_API_URL = "https://datnbeserver.azurewebsites.net";

export const GET_WORKING_PROJECTS_SUCCESS = "GET_WORKING_PROJECTS_SUCCESS";
export const GET_WORKING_PROJECTS_ERROR = "GET_WORKING_PROJECTS_ERROR";
export const GET_PM_PROJECTS_SUCCESS = "GET_PM_PROJECTS_SUCCESS";
export const GET_PM_PROJECTS_ERROR = "GET_PM_PROJECTS_ERROR";
export const GET_PROJECT_EDIT_DETAIL_SUCCESS =
  "GET_PROJECT_EDIT_DETAIL_SUCCESS";
export const GET_PROJECT_EDIT_DETAIL_ERROR = "GET_PROJECT_EDIT_DETAIL_ERROR";
export const CREATE_NEW_PROJECT_SUCCESS = "CREATE_NEW_PROJECT_SUCCESS";
export const CREATE_NEW_PROJECT_ERROR = "CREATE_NEW_PROJECT_ERROR";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";
export const GET_PM_PROJECT_DETAIL_SUCCESS = "GET_PM_PROJECT_DETAIL_SUCCESS";
export const GET_PM_PROJECT_DETAIL_ERROR = "GET_PM_PROJECT_DETAIL_ERROR";
export const ARCHIVE_A_PROJECT_SUCCESS = "ARCHIVE_A_PROJECT_SUCCESS";
export const ARCHIVE_A_PROJECT_ERROR = "ARCHIVE_A_PROJECT_ERROR";
export const UNARCHIVE_A_PROJECT_SUCCESS = "UNARCHIVE_A_PROJECT_SUCCESS";
export const UNARCHIVE_A_PROJECT_ERROR = "UNARCHIVE_A_PROJECT_ERROR";

export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_ERROR = "GET_ALL_USER_ERROR";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_ERROR = "GET_USER_BY_ID_ERROR";
export const ACTIVE_USER_SUCCESS = "ACTIVE_USER_SUCCESS";
export const ACTIVE_USER_ERROR = "ACTIVE_USER_ERROR";
export const DEACTIVE_USER_SUCCESS = "DEACTIVE_USER_SUCCESS";
export const DEACTIVE_USER_ERROR = "DEACTIVE_USER_ERROR";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_ERROR = "UPDATE_USER_ROLE_ERROR";
export const SEND_INVITATION_SUCCESS = "SEND_INVITATION_SUCCESS";
export const SEND_INVITATION_ERROR = "SEND_INVITATION_ERROR";

export const GET_WORKING_HOUR_BY_DATE_SUCCESS =
  "GET_WORKING_HOUR_BY_DATE_SUCCESS";
export const GET_WORKING_HOUR_BY_DATE_ERROR = "GET_WORKING_HOUR_BY_DATE_ERROR";
export const GET_TIME_ENTRIES_BY_DATE_SUCCESS =
  "GET_TIME_ENTRIES_BY_DATE_SUCCESS";
export const GET_TIME_ENTRIES_BY_DATE_ERROR = "GET_TIME_ENTRIES_BY_DATE_ERROR";
export const ADD_TIME_ENTRY_SUCCESS = "ADD_TIME_ENTRY_SUCCESS";
export const ADD_TIME_ENTRY_ERROR = "ADD_TIME_ENTRY_ERROR";
export const GET_USER_TIME_ENTRY_SUCCESS = "GET_USER_TIME_ENTRY_SUCCESS";
export const GET_USER_TIME_ENTRY_ERROR = "GET_USER_TIME_ENTRY_ERROR";
export const DELETE_TIME_ENTRY_SUCCESS = "DELETE_TIME_ENTRY_SUCCESS";
export const DELETE_TIME_ENTRY_ERROR = "DELETE_TIME_ENTRY_ERROR";

export const GET_PERSONAL_REPORT_SUCCESS = "GET_PERSONAL_REPORT_SUCCESS";
export const GET_PERSONAL_REPORT_ERROR = "GET_PERSONAL_REPORT_ERROR";
export const GET_TEAM_REPORT_SUCCESS = "GET_TEAM_REPORT_SUCCESS";
export const GET_TEAM_REPORT_ERROR = "GET_TEAM_REPORT_ERROR";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_ERROR = "GET_REPORT_ERROR";
export const GET_USER_REPORT_SUCCESS = "GET_USER_REPORT_SUCCESS";
export const GET_USER_REPORT_ERROR = "GET_USER_REPORT_ERROR";
export const GET_PROJECT_REPORT_SUCCESS = "GET_PROJECT_REPORT_SUCCESS";
export const GET_PROJECT_REPORT_ERROR = "GET_PROJECT_REPORT_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
